steps:
  - block: "Select Release Version"
    fields:
      - select: "Release Version"
        key: "release-version"
        hint: "Major and minor versions should only be incremented as discussed with your Delivery Lead :fork:"
        required: true
        default: "patch"
        options:
          - label: "Major"
            value: "major"
          - label: "Minor"
            value: "minor"
          - label: "Patch"
            value: "patch"
    branches: "testing-jx"
  - command: './.buildkite/script.sh'
    agents:
      queue: ${QUEUE}
    branches: "testing-jx"